### ISSUE TITLE
resume issue

### ISSUE THREAD

**Issue by fedemantica** [biocorecrg/ExOrthist#23]
The pipeline does not resume from the expected process in all the runs. There might be something wrong with the split_EX_pairs_to_realign and score_EX_matches.

**Comment by lucacozzuto** [comment]
The score_EX_matches is writing in the same folder used as its input. So this breaks the caching system. We have two options: splitting input and output and using the storeDir instead of publishDir. I think the first option is safer and I add this as a bug fix, but if you like more the first input let me know.

**Comment by lucacozzuto** [comment]
Solved at https://github.com/biocorecrg/ExOrthist/commit/107b38d3e7813505ee1f52009ef6a917bb734d46
